   INSERT INTO TRANSFERENCIAS                             
   VALUES                                                 
   (1,1001,1003,150.00,DATE('2026-08-06'),'P');           
   INSERT INTO TRANSFERENCIAS                             
   VALUES                                                 
   (2,1005,1002,1000.00,DATE('2026-08-06'),'P');          
   INSERT INTO TRANSFERENCIAS                             
   VALUES                                                 
   (3,1003,1004,75.50,DATE('2026-08-06'),'P');            
   INSERT INTO TRANSFERENCIAS                             
   VALUES                                                 
   (4,1006,1008,250.00,DATE('2026-08-06'),'P');           
   INSERT INTO TRANSFERENCIAS                             
   VALUES                                                 
   (5,1002,1007,80.00,DATE('2026-08-06'),'P');            
   INSERT INTO TRANSFERENCIAS                             
   VALUES                                                 
   (6,1008,1001,600.00,DATE('2026-08-06'),'P');           
   INSERT INTO TRANSFERENCIAS                             
   VALUES                                                 
   (7,1007,1005,120.00,DATE('2026-08-06'),'P');           
   INSERT INTO TRANSFERENCIAS                             
   VALUES                                                 
   (8,1004,1006,40.00,DATE('2026-08-06'),'P');            
   INSERT INTO TRANSFERENCIAS                             
   VALUES                                                 
   (9,1003,1001,2000.00,DATE('2026-08-06'),'P');          
   INSERT INTO TRANSFERENCIAS                             
   VALUES                                                 
   (10,1001,1005,50.00,DATE('2026-08-06'),'P');    
     INSERT INTO CUENTAS                                             
    VALUES                                                          
    (1001,1,'ES2100010001000000000001',2500.00,'A',                
     ('2024-01-15')); 
                                               
    INSERT INTO CUENTAS                                             
    VALUES                                                          
    (1002,1,'ES2100010001000000000002',1200.00,'A',                 
     ('2024-02-10'));                                               
    INSERT INTO CUENTAS                                             
    VALUES                                                          
    (1003,2,'ES2100010001000000000003',4500.00,'A',                 
     ('2023-09-10'));                                               
    INSERT INTO CUENTAS                                             
    VALUES                                                          
    (1004,3,'ES2100010001000000000004',900.00,'A',                  
     ('2022-05-18'));                                               
    INSERT INTO CUENTAS                                             
    VALUES                                                          
    (1005,4,'ES2100010001000000000005',8200.00,'A',                 
     ('2024-03-02'));                                               
    INSERT INTO CUENTAS                                             
    VALUES                                                          
    (1006,5,'ES2100010001000000000006',1500.00,'A',                 
     ('2021-10-25'));                                               
    INSERT INTO CUENTAS                                             
    VALUES                                                          
    (1007,3,'ES2100010001000000000007',3200.00,'A',                 
     ('2023-06-01'));                                               
    INSERT INTO CUENTAS                                             
    VALUES                                                          
    (1008,2,'ES2100010001000000000008',6000.00,'A',                 
    ('2024-04-20')); 
  
  INSERT INTO CLIENTES                                      
  VALUES                                                    
  (1,'12345678A','NESTOR','GARCIA','GARCIA',                
   '1996-05-31',                                            
   '600111111',                                             
   'NESTOR.GARCIA@BANCO.ES',                                
   'A',                                                     
   ('2024-01-15'));                                         
  INSERT INTO CLIENTES                                      
  VALUES                                                    
  (2,'23456789B','ANA','LOPEZ','MARTIN',                    
   '1988-07-12',                                            
   '600222222',                                             
   'ANA.LOPEZ@BANCO.ES',                                    
   'A',                                                     
   ('2023-09-10'));                                         
  INSERT INTO CLIENTES                                      
  VALUES                                                    
  (3,'34567890C','CARLOS','PEREZ','SANTOS',                 
   '1979-11-21',                                            
   '600333333',                                             
   'CARLOS.PEREZ@BANCO.ES',                                 
   'A',                                                     
   ('2022-05-18'));                                         
  INSERT INTO CLIENTES                                      
  VALUES                                                    
  (4,'45678901D','LAURA','MARTIN','GOMEZ',                  
   '1992-02-08',                                            
   '600444444',                                             
   'LAURA.MARTIN@BANCO.ES',                                 
   'A',                                                     
   ('2024-03-02'));                                         
  INSERT INTO CLIENTES                                      
  VALUES                                                    
  (5,'56789012E','DAVID','RUIZ','FERNANDEZ',                
   '1985-09-14',                                            
   '600555555',                                             
   'DAVID.RUIZ@BANCO.ES',                                                                                         
